image: java:11

pipelines:
  default:
    - step:
        name: Build and Deploy to Firebase
        caches:
          - gradle
          - android-sdk
        script:
          - apt-get update && apt-get install -y wget
          - wget "https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip" -O cmdline-tools.zip
          - unzip cmdline-tools.zip -d $ANDROID_HOME/
          - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
          - $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          - ./gradlew assembleRelease
          - ./gradlew appDistributionUploadRelease
        artifacts:
          - app/build/outputs/**

definitions:
  caches:
    gradle: ~/.gradle
    android-sdk: $ANDROID_HOME
